### PR TITLE
add travis-ci file and CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by KeyboardInterrupt**

### CODE REVIEW

**Comment by KeyboardInterrupt** [comment]
Whoops, This PR Should have been to my Fork. Sorry.

**Comment by walterheck** [comment]
Can I still merge it here also? Seems useful :)

**Comment by KeyboardInterrupt** [comment]
Yes of course, I will fix all the Stuff the CI test raises, I will then open up another PR

You can take a first look at the Issues it raises here:
https://travis-ci.com/awesome-devops/awesome-puppet/builds/89348311
There are a few.

**Comment by KeyboardInterrupt** [comment]
https://travis-ci.com/awesome-devops/awesome-puppet/builds/89357420 It now passes `mdl` and `awesome_bot`

**Pull request merged**
