### PR TITLE
Add puppet-lint-action

### PR DESCRIPTION
**Pull request by ScottBrenner**
Proposing adding

> [puppet-lint-action](https://github.com/marketplace/actions/puppet-lint-action) GitHub Action for interacting with Puppet Lint

### CODE REVIEW

**Comment by ScottBrenner** [comment]
@KeyboardInterrupt Mind reviewing?

**Comment by KeyboardInterrupt** [comment]
I think this is a useful Addition, and I will gladly integrate it into the Fork https://github.com/awesome-devops/awesome-puppet
I cannot Review and add it here though, as this is the Repository of @olindata .
Greetings.

**Comment by walterheck** [comment]
Apologies for the late action on this. @KeyboardInterrupt should we look at either making you a contributor to this repo or deprecating this one and making yours active? No point in having two active repo's :)

**Comment by KeyboardInterrupt** [comment]
@walterheck I did not plan a take over, my Fork initially was just to add Travis-CI ^^ and as our. repos are essentially the same, one can be closed.

I will close the Fork, If you want to, you can attribute me the contributor Role.
Greetings.

**Comment by walterheck** [comment]
@KeyboardInterrupt done, welcome :)

**Pull request merged**
